#red de hopfield

entrenamiento

In [3]:
#red de hopfield
import numpy as np
import cv2


# Función de activación para la red Hopfield
def activacion(patron):
    return np.where(patron >= 0, 1, -1)


# Red Hopfield
class RedHopfield:
    def __init__(self, tamaño):
        self.tamaño = tamaño
        self.pesos = np.zeros((tamaño, tamaño))

    def entrenar(self, patrones):
        print("Entrenando la red Hopfield...")
        for idx, patron in enumerate(patrones):
            patron = patron.reshape(-1, 1)
            self.pesos += np.dot(patron, patron.T)
            np.fill_diagonal(self.pesos, 0)  # Las neuronas no se conectan entre sí
            print(f"\nPesos después de entrenar el patrón {idx + 1} ({['Rojo', 'Amarillo', 'Verde'][idx]}):")
            print(self.pesos)

    def reconocer(self, entrada):
        entrada = entrada.reshape(-1, 1)
        salida = np.copy(entrada)
        iteracion = 0
        while True:
            iteracion += 1
            salida_anterior = salida.copy()
            salida = activacion(np.dot(self.pesos, salida))

            # Imprimir los pesos y la salida en cada iteración
            print(f"\nIteración {iteracion} de reconocimiento:")
            print("Pesos actuales:")
            print(self.pesos)
            print("Salida actual:")
            print(salida.flatten())

            if np.array_equal(salida, salida_anterior):
                break
        return salida.flatten()


# Crear los patrones para los colores del semáforo
rojo = np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])  # Color Rojo
amarillo = np.array([-1, 1, -1, 1, -1, 1, -1, 1, -1])  # Color Amarillo
verde = np.array([-1, -1, 1, -1, -1, 1, 1, -1, -1])  # Color Verde

# Entrenamiento
patrones = [rojo, amarillo, verde]
red = RedHopfield(tamaño=9)
red.entrenar(patrones)

# Guardar los pesos entrenados
np.save('entrenamientos_guardados/pesos_hopfield.npy', red.pesos)
print("\nEntrenamiento completado. Pesos guardados como 'pesos_hopfield.npy'.\n")

# Ejemplo de reconocimiento
entrada = np.array([-1, -1, -1, -1, 1, 1, -1, -1, -1])  # Ejemplo de entrada para "rojo"
print("Reconociendo la entrada:")
reconocimiento = red.reconocer(entrada)
print(f"\nPatrón reconocido: {reconocimiento}")


Entrenando la red Hopfield...

Pesos después de entrenar el patrón 1 (Rojo):
[[ 0. -1. -1. -1.  1. -1. -1. -1.  1.]
 [-1.  0.  1.  1. -1.  1.  1.  1. -1.]
 [-1.  1.  0.  1. -1.  1.  1.  1. -1.]
 [-1.  1.  1.  0. -1.  1.  1.  1. -1.]
 [ 1. -1. -1. -1.  0. -1. -1. -1.  1.]
 [-1.  1.  1.  1. -1.  0.  1.  1. -1.]
 [-1.  1.  1.  1. -1.  1.  0.  1. -1.]
 [-1.  1.  1.  1. -1.  1.  1.  0. -1.]
 [ 1. -1. -1. -1.  1. -1. -1. -1.  0.]]

Pesos después de entrenar el patrón 2 (Amarillo):
[[ 0. -2.  0. -2.  2. -2.  0. -2.  2.]
 [-2.  0.  0.  2. -2.  2.  0.  2. -2.]
 [ 0.  0.  0.  0.  0.  0.  2.  0.  0.]
 [-2.  2.  0.  0. -2.  2.  0.  2. -2.]
 [ 2. -2.  0. -2.  0. -2.  0. -2.  2.]
 [-2.  2.  0.  2. -2.  0.  0.  2. -2.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.  0.]
 [-2.  2.  0.  2. -2.  2.  0.  0. -2.]
 [ 2. -2.  0. -2.  2. -2.  0. -2.  0.]]

Pesos después de entrenar el patrón 3 (Verde):
[[ 0. -1. -1. -1.  3. -3. -1. -1.  3.]
 [-1.  0. -1.  3. -1.  1. -1.  3. -1.]
 [-1. -1.  0. -1. -1.  1.  3. -1. -1.]
 [-

Ejecucion

In [4]:

import cv2
import numpy as np


# Función de activación para la red Hopfield
def activacion(patron):
    return np.where(patron >= 0, 1, -1)


# Red Hopfield
class RedHopfield:
    def __init__(self, tamaño, pesos):
        self.tamaño = tamaño
        self.pesos = pesos

    def reconocer(self, entrada):
        entrada = entrada.reshape(-1, 1)
        salida = np.copy(entrada)
        while True:
            salida_anterior = salida.copy()
            salida = activacion(np.dot(self.pesos, salida))
            if np.array_equal(salida, salida_anterior):
                break
        return salida.flatten()


# Función para identificar el color basado en la entrada
def identificar_color(frame):
    # Convertir la imagen a espacio de color HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # Definir los rangos de color para rojo, amarillo y verde
    # Rojo
    rojo_bajo = np.array([0, 120, 70])
    rojo_alto = np.array([10, 255, 255])
    rojo_mask = cv2.inRange(hsv, rojo_bajo, rojo_alto)

    # Amarillo
    amarillo_bajo = np.array([20, 100, 100])
    amarillo_alto = np.array([40, 255, 255])
    amarillo_mask = cv2.inRange(hsv, amarillo_bajo, amarillo_alto)

    # Verde
    verde_bajo = np.array([35, 50, 50])
    verde_alto = np.array([85, 255, 255])
    verde_mask = cv2.inRange(hsv, verde_bajo, verde_alto)

    # Contar los píxeles de cada color
    rojo_cont = np.sum(rojo_mask)
    amarillo_cont = np.sum(amarillo_mask)
    verde_cont = np.sum(verde_mask)

    # convertir color en matriz
    if rojo_cont > max(amarillo_cont, verde_cont):
        return np.array([1, 1, -1, -1, 1, -1, -1, -1, -1])  # Rojo
    elif verde_cont > max(rojo_cont, amarillo_cont):
        return np.array([-1, -1, 1, -1, -1, 1, 1, -1, 1])  # Verde
    else:
        return np.array([-1, 1, -1, 1, -1, 1, -1, 1, 1])  # Amarillo


def iniciarCamara():
    print("Iniciando módulo")
    cam = cv2.VideoCapture(0)
    if not cam.isOpened():
        print("No se pudo abrir la cámara")
        return
    print("Cámara abierta")

    # Cargar los pesos entrenados
    try:
        pesos_hopfield = np.load('entrenamientos_guardados/pesos_hopfield.npy')
        print("Pesos de la red Hopfield cargados correctamente.")
    except Exception as e:
        print(f"Error al cargar los pesos entrenados: {e}")
        return

    # Crear la red Hopfield con los pesos cargados
    red = RedHopfield(tamaño=9, pesos=pesos_hopfield)

    while True:
        ret, frame = cam.read()
        if not ret:
            print("Error al encontrar imagen")
            break

        # Extraer color y predecir usando la red Hopfield
        entrada = identificar_color(frame)
        color_identificado = red.reconocer(entrada)

        # Determinar el color predicho
        if np.array_equal(color_identificado, np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])):  # Rojo
            texto = "Semáforo: Rojo - Deténgase"
        elif np.array_equal(color_identificado, np.array([-1, -1, 1, -1, -1, 1, 1, -1, -1])):  # Verde
            texto = "Semáforo: Verde - Puede avanzar"
        else:  # Amarillo
            texto = "Semáforo: Amarillo - Precaución"

        # Mostrar el texto en la imagen de la cámara
        cv2.putText(frame, texto, (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)

        # Mostrar el frame con el texto
        cv2.imshow("Cámara", frame)

        key = cv2.waitKey(1) & 0xFF
        if key == 27:  # Escape para salir
            break

    cam.release()
    cv2.destroyAllWindows()


# Ejecutar la cámara
if __name__ == "__main__":
    iniciarCamara()

Iniciando módulo
Cámara abierta
Pesos de la red Hopfield cargados correctamente.


codigo para probar

In [6]:
import cv2
import numpy as np
import time
import psutil

# Función de activación para la red Hopfield
def activacion(patron):
    return np.where(patron >= 0, 1, -1)

# Red Hopfield
class RedHopfield:
    def __init__(self, tamaño, pesos):
        self.tamaño = tamaño
        self.pesos = pesos

    def reconocer(self, entrada):
        entrada = entrada.reshape(-1, 1)
        salida = np.copy(entrada)
        while True:
            salida_anterior = salida.copy()
            salida = activacion(np.dot(self.pesos, salida))
            if np.array_equal(salida, salida_anterior):
                break
        return salida.flatten()

# Función para identificar el color basado en la entrada
def identificar_color(frame):
    # Convertir la imagen a espacio de color HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # Definir los rangos de color para rojo, amarillo y verde
    rojo_bajo = np.array([0, 120, 70])
    rojo_alto = np.array([10, 255, 255])
    rojo_mask = cv2.inRange(hsv, rojo_bajo, rojo_alto)

    amarillo_bajo = np.array([20, 100, 100])
    amarillo_alto = np.array([40, 255, 255])
    amarillo_mask = cv2.inRange(hsv, amarillo_bajo, amarillo_alto)

    verde_bajo = np.array([35, 50, 50])
    verde_alto = np.array([85, 255, 255])
    verde_mask = cv2.inRange(hsv, verde_bajo, verde_alto)

    rojo_cont = np.sum(rojo_mask)
    amarillo_cont = np.sum(amarillo_mask)
    verde_cont = np.sum(verde_mask)

    if rojo_cont > max(amarillo_cont, verde_cont):
        return np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])  # Rojo
    elif verde_cont > max(rojo_cont, amarillo_cont):
        return np.array([-1, -1, 1, -1, -1, 1, 1, -1, -1])  # Verde
    else:
        return np.array([-1, 1, -1, 1, -1, 1, -1, 1, -1])  # Amarillo

def iniciarCamara(color_objetivo='rojo'):
    print("Iniciando módulo")
    cam = cv2.VideoCapture(0)
    if not cam.isOpened():
        print("No se pudo abrir la cámara")
        return
    print("Cámara abierta")

    # Cargar los pesos entrenados
    try:
        pesos_hopfield = np.load('entrenamientos_guardados/pesos_hopfield.npy')
        print("Pesos de la red Hopfield cargados correctamente.")
    except Exception as e:
        print(f"Error al cargar los pesos entrenados: {e}")
        return

    # Crear la red Hopfield con los pesos cargados
    red = RedHopfield(tamaño=9, pesos=pesos_hopfield)

    # Criterios Cuantitativos
    predicciones_correctas = 0
    total_predicciones = 0
    errores = 0
    tiempos = []

    # Para el uso de recursos
    proceso = psutil.Process()

    # Define el color objetivo para medir precisión (rojo, amarillo o verde)
    if color_objetivo == 'rojo':
        color_real = np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])  # Color Rojo
    elif color_objetivo == 'amarillo':
        color_real = np.array([-1, 1, -1, 1, -1, 1, -1, 1, -1])  # Color Amarillo
    elif color_objetivo == 'verde':
        color_real = np.array([-1, -1, 1, -1, -1, 1, 1, -1, -1])  # Color Verde
    else:
        print(f"Color no válido: {color_objetivo}. Usando rojo por defecto.")
        color_real = np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])  # Color Rojo

    while True:
        ret, frame = cam.read()
        if not ret:
            print("Error al encontrar imagen")
            break

        # Extraer color y predecir usando la red Hopfield
        entrada = identificar_color(frame)
        start_time = time.time()

        color_identificado = red.reconocer(entrada)

        # Medir el tiempo de ejecución
        end_time = time.time()
        tiempos.append(end_time - start_time)

        # Determinar el color predicho y el valor real
        if np.array_equal(color_identificado, color_real):
            texto = f"Semáforo: {color_objetivo.capitalize()} - Predicción Correcta"
            predicciones_correctas += 1
        else:
            texto = f"Semáforo: {color_objetivo.capitalize()} - Predicción Incorrecta"
            errores += 1

        # Actualizar el contador de predicciones
        total_predicciones += 1

        # Mostrar el texto en la imagen de la cámara
        cv2.putText(frame, texto, (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)

        # Mostrar el frame con el texto
        cv2.imshow("Cámara", frame)

        key = cv2.waitKey(1) & 0xFF
        if key == 27:  # Escape para salir
            break

    # Calcular precisión y otros criterios
    precision = predicciones_correctas / total_predicciones
    latencia_media = np.mean(tiempos) * 1000  # en milisegundos
    uso_cpu = proceso.cpu_percent(interval=1)
    uso_memoria = proceso.memory_info().rss / 1024 / 1024  # en MB

    print(f"\nCriterios Cuantitativos para el color {color_objetivo.capitalize()}:")
    print(f"Precisión: {precision * 100:.2f}%")
    print(f"Latencia Media: {latencia_media:.2f} ms")
    print(f"Uso de CPU: {uso_cpu:.2f}%")
    print(f"Uso de Memoria: {uso_memoria:.2f} MB")
    print(f"Tasa de Error: {errores / total_predicciones * 100:.2f}%")

    cam.release()
    cv2.destroyAllWindows()

# Ejecutar la cámara, evaluando el color rojo
if __name__ == "__main__":
    iniciarCamara(color_objetivo='rojo')  # Puedes cambiar 'rojo' por 'amarillo' o 'verde'

Iniciando módulo
Cámara abierta
Pesos de la red Hopfield cargados correctamente.

Criterios Cuantitativos para el color Rojo:
Precisión: 87.68%
Latencia Media: 0.01 ms
Uso de CPU: 0.00%
Uso de Memoria: 112.73 MB
Tasa de Error: 12.32%
