In [ ]:
import cv2

def iniciarCamara():
    print("iniciando modulo")
    cam = cv2.VideoCapture(0)
    if not cam.isOpened():
        print("No se pudo abrir la cámara")
        return
    print("Camara Abierta")
    while True:
        ret, frame = cam.read()
        if not ret:
            print("Error al encontrar imagen")
            break
        cv2.imshow("camara 1", frame)  # <- aquí estaba el error
        key = cv2.waitKey(1) & 0xFF
        if key == 27:  # Esc para salir
            break
        rojo = frame[:,:,1]
        cv2.imshow("Capa Roja",rojo)
    cam.release()
    cv2.destroyAllWindows()

# Este bloque previene que se ejecute dos veces si lo importas en otro script
if __name__ == "__main__":
    iniciarCamara()

red MLP

In [ ]:
#red mlp

In [1]:
# entrenamiento.py
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import time
import psutil  # Para uso de recursos (CPU y Memoria)

# Definir el modelo MLP
def crear_modelo():
    modelo = Sequential()
    modelo.add(Dense(64, input_dim=3, activation='relu'))  # 3 características (promedio de R, G, B)
    modelo.add(Dense(32, activation='relu'))
    modelo.add(Dense(3, activation='softmax'))  # 3 clases: rojo, amarillo, verde
    modelo.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return modelo

# Generar datos de entrenamiento
def generar_datos(n=1000):
    X_train = []
    y_train = []

    for _ in range(n):
        R = np.random.randint(0, 256)
        G = np.random.randint(0, 256)
        B = np.random.randint(0, 256)

        X_train.append([R, G, B])

        if R > G and R > B:
            y_train.append(0)  # Rojo
        elif G > R and G > B:
            y_train.append(1)  # Amarillo
        else:
            y_train.append(2)  # Verde

    return np.array(X_train), np.array(y_train)

# Función para evaluar precisión y tasa de error en los datos de prueba
def evaluar_precision(modelo, X_test, y_test):
    predicciones = modelo.predict(X_test)
    y_pred = np.argmax(predicciones, axis=1)
    y_true = np.argmax(y_test, axis=1)

    correctas = np.sum(y_pred == y_true)
    total = len(y_true)
    precision = correctas / total
    tasa_error = 1 - precision

    return precision, tasa_error

# Entrenar la red neuronal con los datos generados
def entrenar_red():
    # Generar conjunto de datos
    X_train, y_train = generar_datos(10000)  # 10,000 ejemplos

    encoder = LabelEncoder()
    y_train_encoded = encoder.fit_transform(y_train)
    y_train_onehot = tf.keras.utils.to_categorical(y_train_encoded, 3)

    # Dividir datos en entrenamiento y validación
    X_train, X_val, y_train, y_val = train_test_split(X_train, y_train_onehot, test_size=0.2, random_state=42)

    # Crear modelo
    modelo = crear_modelo()

    # Medir tiempo de entrenamiento
    start_time = time.time()
    modelo.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_val, y_val), verbose=1)
    end_time = time.time()

    # Tiempo de entrenamiento
    tiempo_entrenamiento = end_time - start_time
    print(f"Tiempo de entrenamiento: {tiempo_entrenamiento:.2f} segundos")

    # Evaluar precisión y tasa de error en datos de validación
    precision, tasa_error = evaluar_precision(modelo, X_val, y_val)
    print(f"Precisión en datos de validación: {precision * 100:.2f}%")
    print(f"Tasa de error en datos de validación: {tasa_error * 100:.2f}%")

    # Guardar el modelo entrenado
    modelo.save("modelo_semaforo.h5")
    print("Modelo guardado como 'modelo_semaforo.h5'")

if __name__ == "__main__":
    entrenar_red()


Epoch 1/50


C:\Users\Equipo\PycharmProjects\JupyterProject\.venv\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7853 - loss: 4.6267 - val_accuracy: 0.9600 - val_loss: 0.1144
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9696 - loss: 0.1014 - val_accuracy: 0.9400 - val_loss: 0.1829
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9781 - loss: 0.0829 - val_accuracy: 0.9745 - val_loss: 0.0553
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9704 - loss: 0.0844 - val_accuracy: 0.9435 - val_loss: 0.1664
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9829 - loss: 0.0483 - val_accuracy: 0.9835 - val_loss: 0.0482
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9727 - loss: 0.0856 - val_accuracy: 0.9885 - val_loss: 0.0294
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9795 - loss: 0.0566 - val_accuracy: 0.9835 - val_loss: 0.0364
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9771 - loss: 0.0584 - val_accuracy: 0.9610 - val_


Tasa de error en datos de validación: 1.45%
Modelo guardado como 'modelo_semaforo.h5'


In [ ]:
# prediccion.py
import cv2
import numpy as np
import tensorflow as tf
import time
import psutil  # Para uso de recursos (CPU y Memoria)

# Cargar el modelo previamente entrenado
modelo = tf.keras.models.load_model("entrenamientos_guardados/modelo_semaforo.h5")

# Preprocesar la imagen para extraer los colores predominantes
def obtener_color_promedio(frame):
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    rango_rojo = ((0, 100, 100), (10, 255, 255))
    rango_amarillo = ((20, 100, 100), (40, 255, 255))
    rango_verde = ((40, 100, 100), (80, 255, 255))

    rojo = cv2.inRange(hsv, rango_rojo[0], rango_rojo[1])
    amarillo = cv2.inRange(hsv, rango_amarillo[0], rango_amarillo[1])
    verde = cv2.inRange(hsv, rango_verde[0], rango_verde[1])

    promedio_rojo = cv2.countNonZero(rojo)
    promedio_amarillo = cv2.countNonZero(amarillo)
    promedio_verde = cv2.countNonZero(verde)

    return np.array([promedio_rojo, promedio_amarillo, promedio_verde])

# Función para predecir el color del semáforo en tiempo real
def predecir_color(frame):
    promedio_colores = obtener_color_promedio(frame)
    start_time = time.time()
    prediccion = modelo.predict(np.array([promedio_colores]), verbose=0)
    end_time = time.time()

    # Medir tiempo de ejecución
    tiempo_ejecucion = (end_time - start_time) * 1000  # en milisegundos

    clase_predicha = np.argmax(prediccion)

    if clase_predicha == 0:
        color_predicho = "Semaforo: Rojo - Detengase"
    elif clase_predicha == 1:
        color_predicho = "Semaforo: Amarillo - Precaucion"
    elif clase_predicha == 2:
        color_predicho = "Semaforo: Verde - Puede avanzar"

    return color_predicho, tiempo_ejecucion

# Iniciar la cámara y usar el modelo para predecir el color del semáforo
def iniciarCamara():
    print("Iniciando módulo de cámara...")
    cam = cv2.VideoCapture(0)

    if not cam.isOpened():
        print("No se pudo abrir la cámara")
        return

    print("Cámara abierta")

    predicciones_correctas = 0
    total_predicciones = 0

    while True:
        ret, frame = cam.read()
        if not ret:
            print("Error al capturar imagen")
            break

        color_predicho, tiempo_ejecucion = predecir_color(frame)

        # Actualizar estadísticas
        total_predicciones += 1
        if color_predicho == "Semaforo: Rojo - Detengase":  # Suponiendo que sea el color correcto
            predicciones_correctas += 1

        precision = predicciones_correctas / total_predicciones
        print(f"Precisión: {precision * 100:.2f}%")
        print(f"Tiempo de ejecución (frame): {tiempo_ejecucion:.2f} ms")

        # Mostrar información en la pantalla
        cv2.putText(frame, f"Color: {color_predicho}", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        cv2.putText(frame, f"Tiempo: {tiempo_ejecucion:.2f} ms", (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        cv2.imshow("Camara", frame)

        key = cv2.waitKey(1) & 0xFF
        if key == 27:  # ESC
            break

    cam.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    iniciarCamara()


Iniciando módulo de cámara...
Cámara abierta
Precisión: 0.00%
Tiempo de ejecución (frame): 137.69 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 75.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 78.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 92.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 70.99 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 73.06 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 83.02 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 73.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 199.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 79.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 78.48 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 86.01 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 80.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 77.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 83.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 77.00 ms
Precisión: 0.00%
Tiempo de ejecución (frame): 77.04 ms
Precisión: 0.00%
T

#red de hopfield

In [ ]:
#red de hopfield

In [1]:
#red de hopfield
import numpy as np
import cv2


# Función de activación para la red Hopfield
def activacion(patron):
    return np.where(patron >= 0, 1, -1)


# Red Hopfield
class RedHopfield:
    def __init__(self, tamaño):
        self.tamaño = tamaño
        self.pesos = np.zeros((tamaño, tamaño))

    def entrenar(self, patrones):
        print("Entrenando la red Hopfield...")
        for idx, patron in enumerate(patrones):
            patron = patron.reshape(-1, 1)
            self.pesos += np.dot(patron, patron.T)
            np.fill_diagonal(self.pesos, 0)  # Las neuronas no se conectan entre sí
            print(f"\nPesos después de entrenar el patrón {idx + 1} ({['Rojo', 'Amarillo', 'Verde'][idx]}):")
            print(self.pesos)

    def reconocer(self, entrada):
        entrada = entrada.reshape(-1, 1)
        salida = np.copy(entrada)
        iteracion = 0
        while True:
            iteracion += 1
            salida_anterior = salida.copy()
            salida = activacion(np.dot(self.pesos, salida))

            # Imprimir los pesos y la salida en cada iteración
            print(f"\nIteración {iteracion} de reconocimiento:")
            print("Pesos actuales:")
            print(self.pesos)
            print("Salida actual:")
            print(salida.flatten())

            if np.array_equal(salida, salida_anterior):
                break
        return salida.flatten()


# Crear los patrones para los colores del semáforo
rojo = np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])  # Color Rojo
amarillo = np.array([-1, 1, -1, 1, -1, 1, -1, 1, -1])  # Color Amarillo
verde = np.array([-1, -1, 1, -1, -1, 1, 1, -1, -1])  # Color Verde

# Entrenamiento
patrones = [rojo, amarillo, verde]
red = RedHopfield(tamaño=9)
red.entrenar(patrones)

# Guardar los pesos entrenados
np.save('entrenamientos_guardados/pesos_hopfield.npy', red.pesos)
print("\nEntrenamiento completado. Pesos guardados como 'pesos_hopfield.npy'.\n")

# Ejemplo de reconocimiento
entrada = np.array([-1, -1, -1, -1, 1, 1, -1, -1, -1])  # Ejemplo de entrada para "rojo"
print("Reconociendo la entrada:")
reconocimiento = red.reconocer(entrada)
print(f"\nPatrón reconocido: {reconocimiento}")


Entrenando la red Hopfield...

Pesos después de entrenar el patrón 1 (Rojo):
[[ 0. -1. -1. -1.  1. -1. -1. -1.  1.]
 [-1.  0.  1.  1. -1.  1.  1.  1. -1.]
 [-1.  1.  0.  1. -1.  1.  1.  1. -1.]
 [-1.  1.  1.  0. -1.  1.  1.  1. -1.]
 [ 1. -1. -1. -1.  0. -1. -1. -1.  1.]
 [-1.  1.  1.  1. -1.  0.  1.  1. -1.]
 [-1.  1.  1.  1. -1.  1.  0.  1. -1.]
 [-1.  1.  1.  1. -1.  1.  1.  0. -1.]
 [ 1. -1. -1. -1.  1. -1. -1. -1.  0.]]

Pesos después de entrenar el patrón 2 (Amarillo):
[[ 0. -2.  0. -2.  2. -2.  0. -2.  2.]
 [-2.  0.  0.  2. -2.  2.  0.  2. -2.]
 [ 0.  0.  0.  0.  0.  0.  2.  0.  0.]
 [-2.  2.  0.  0. -2.  2.  0.  2. -2.]
 [ 2. -2.  0. -2.  0. -2.  0. -2.  2.]
 [-2.  2.  0.  2. -2.  0.  0.  2. -2.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.  0.]
 [-2.  2.  0.  2. -2.  2.  0.  0. -2.]
 [ 2. -2.  0. -2.  2. -2.  0. -2.  0.]]

Pesos después de entrenar el patrón 3 (Verde):
[[ 0. -1. -1. -1.  3. -3. -1. -1.  3.]
 [-1.  0. -1.  3. -1.  1. -1.  3. -1.]
 [-1. -1.  0. -1. -1.  1.  3. -1. -1.]
 [-

In [2]:

import cv2
import numpy as np


# Función de activación para la red Hopfield
def activacion(patron):
    return np.where(patron >= 0, 1, -1)


# Red Hopfield
class RedHopfield:
    def __init__(self, tamaño, pesos):
        self.tamaño = tamaño
        self.pesos = pesos

    def reconocer(self, entrada):
        entrada = entrada.reshape(-1, 1)
        salida = np.copy(entrada)
        while True:
            salida_anterior = salida.copy()
            salida = activacion(np.dot(self.pesos, salida))
            if np.array_equal(salida, salida_anterior):
                break
        return salida.flatten()


# Función para identificar el color basado en la entrada
def identificar_color(frame):
    # Convertir la imagen a espacio de color HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # Definir los rangos de color para rojo, amarillo y verde
    # Rojo
    rojo_bajo = np.array([0, 120, 70])
    rojo_alto = np.array([10, 255, 255])
    rojo_mask = cv2.inRange(hsv, rojo_bajo, rojo_alto)

    # Amarillo
    amarillo_bajo = np.array([20, 100, 100])
    amarillo_alto = np.array([40, 255, 255])
    amarillo_mask = cv2.inRange(hsv, amarillo_bajo, amarillo_alto)

    # Verde
    verde_bajo = np.array([35, 50, 50])
    verde_alto = np.array([85, 255, 255])
    verde_mask = cv2.inRange(hsv, verde_bajo, verde_alto)

    # Contar los píxeles de cada color
    rojo_cont = np.sum(rojo_mask)
    amarillo_cont = np.sum(amarillo_mask)
    verde_cont = np.sum(verde_mask)

    # Decidir el color predominante
    if rojo_cont > max(amarillo_cont, verde_cont):
        return np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])  # Rojo
    elif verde_cont > max(rojo_cont, amarillo_cont):
        return np.array([-1, -1, 1, -1, -1, 1, 1, -1, -1])  # Verde
    else:
        return np.array([-1, 1, -1, 1, -1, 1, -1, 1, -1])  # Amarillo


def iniciarCamara():
    print("Iniciando módulo")
    cam = cv2.VideoCapture(0)
    if not cam.isOpened():
        print("No se pudo abrir la cámara")
        return
    print("Cámara abierta")

    # Cargar los pesos entrenados
    try:
        pesos_hopfield = np.load('entrenamientos_guardados/pesos_hopfield.npy')
        print("Pesos de la red Hopfield cargados correctamente.")
    except Exception as e:
        print(f"Error al cargar los pesos entrenados: {e}")
        return

    # Crear la red Hopfield con los pesos cargados
    red = RedHopfield(tamaño=9, pesos=pesos_hopfield)

    while True:
        ret, frame = cam.read()
        if not ret:
            print("Error al encontrar imagen")
            break

        # Extraer color y predecir usando la red Hopfield
        entrada = identificar_color(frame)
        color_identificado = red.reconocer(entrada)

        # Determinar el color predicho
        if np.array_equal(color_identificado, np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])):  # Rojo
            texto = "Semáforo: Rojo - Deténgase"
        elif np.array_equal(color_identificado, np.array([-1, -1, 1, -1, -1, 1, 1, -1, -1])):  # Verde
            texto = "Semáforo: Verde - Puede avanzar"
        else:  # Amarillo
            texto = "Semáforo: Amarillo - Precaución"

        # Mostrar el texto en la imagen de la cámara
        cv2.putText(frame, texto, (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)

        # Mostrar el frame con el texto
        cv2.imshow("Cámara", frame)

        key = cv2.waitKey(1) & 0xFF
        if key == 27:  # Escape para salir
            break

    cam.release()
    cv2.destroyAllWindows()


# Ejecutar la cámara
if __name__ == "__main__":
    iniciarCamara()

Iniciando módulo
Cámara abierta
Pesos de la red Hopfield cargados correctamente.


In [ ]:
#codigo de datos cuantitativos

In [2]:
import cv2
import numpy as np
import time
import psutil

# Función de activación para la red Hopfield
def activacion(patron):
    return np.where(patron >= 0, 1, -1)

# Red Hopfield
class RedHopfield:
    def __init__(self, tamaño, pesos):
        self.tamaño = tamaño
        self.pesos = pesos

    def reconocer(self, entrada):
        entrada = entrada.reshape(-1, 1)
        salida = np.copy(entrada)
        while True:
            salida_anterior = salida.copy()
            salida = activacion(np.dot(self.pesos, salida))
            if np.array_equal(salida, salida_anterior):
                break
        return salida.flatten()

# Función para identificar el color basado en la entrada
def identificar_color(frame):
    # Convertir la imagen a espacio de color HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # Definir los rangos de color para rojo, amarillo y verde
    rojo_bajo = np.array([0, 120, 70])
    rojo_alto = np.array([10, 255, 255])
    rojo_mask = cv2.inRange(hsv, rojo_bajo, rojo_alto)

    amarillo_bajo = np.array([20, 100, 100])
    amarillo_alto = np.array([40, 255, 255])
    amarillo_mask = cv2.inRange(hsv, amarillo_bajo, amarillo_alto)

    verde_bajo = np.array([35, 50, 50])
    verde_alto = np.array([85, 255, 255])
    verde_mask = cv2.inRange(hsv, verde_bajo, verde_alto)

    rojo_cont = np.sum(rojo_mask)
    amarillo_cont = np.sum(amarillo_mask)
    verde_cont = np.sum(verde_mask)

    if rojo_cont > max(amarillo_cont, verde_cont):
        return np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])  # Rojo
    elif verde_cont > max(rojo_cont, amarillo_cont):
        return np.array([-1, -1, 1, -1, -1, 1, 1, -1, -1])  # Verde
    else:
        return np.array([-1, 1, -1, 1, -1, 1, -1, 1, -1])  # Amarillo

def iniciarCamara(color_objetivo='rojo'):
    print("Iniciando módulo")
    cam = cv2.VideoCapture(0)
    if not cam.isOpened():
        print("No se pudo abrir la cámara")
        return
    print("Cámara abierta")

    # Cargar los pesos entrenados
    try:
        pesos_hopfield = np.load('entrenamientos_guardados/pesos_hopfield.npy')
        print("Pesos de la red Hopfield cargados correctamente.")
    except Exception as e:
        print(f"Error al cargar los pesos entrenados: {e}")
        return

    # Crear la red Hopfield con los pesos cargados
    red = RedHopfield(tamaño=9, pesos=pesos_hopfield)

    # Criterios Cuantitativos
    predicciones_correctas = 0
    total_predicciones = 0
    errores = 0
    tiempos = []

    # Para el uso de recursos
    proceso = psutil.Process()

    # Define el color objetivo para medir precisión (rojo, amarillo o verde)
    if color_objetivo == 'rojo':
        color_real = np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])  # Color Rojo
    elif color_objetivo == 'amarillo':
        color_real = np.array([-1, 1, -1, 1, -1, 1, -1, 1, -1])  # Color Amarillo
    elif color_objetivo == 'verde':
        color_real = np.array([-1, -1, 1, -1, -1, 1, 1, -1, -1])  # Color Verde
    else:
        print(f"Color no válido: {color_objetivo}. Usando rojo por defecto.")
        color_real = np.array([1, -1, -1, -1, 1, -1, -1, -1, 1])  # Color Rojo

    while True:
        ret, frame = cam.read()
        if not ret:
            print("Error al encontrar imagen")
            break

        # Extraer color y predecir usando la red Hopfield
        entrada = identificar_color(frame)
        start_time = time.time()

        color_identificado = red.reconocer(entrada)

        # Medir el tiempo de ejecución
        end_time = time.time()
        tiempos.append(end_time - start_time)

        # Determinar el color predicho y el valor real
        if np.array_equal(color_identificado, color_real):
            texto = f"Semáforo: {color_objetivo.capitalize()} - Predicción Correcta"
            predicciones_correctas += 1
        else:
            texto = f"Semáforo: {color_objetivo.capitalize()} - Predicción Incorrecta"
            errores += 1

        # Actualizar el contador de predicciones
        total_predicciones += 1

        # Mostrar el texto en la imagen de la cámara
        cv2.putText(frame, texto, (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)

        # Mostrar el frame con el texto
        cv2.imshow("Cámara", frame)

        key = cv2.waitKey(1) & 0xFF
        if key == 27:  # Escape para salir
            break

    # Calcular precisión y otros criterios
    precision = predicciones_correctas / total_predicciones
    latencia_media = np.mean(tiempos) * 1000  # en milisegundos
    uso_cpu = proceso.cpu_percent(interval=1)
    uso_memoria = proceso.memory_info().rss / 1024 / 1024  # en MB

    print(f"\nCriterios Cuantitativos para el color {color_objetivo.capitalize()}:")
    print(f"Precisión: {precision * 100:.2f}%")
    print(f"Latencia Media: {latencia_media:.2f} ms")
    print(f"Uso de CPU: {uso_cpu:.2f}%")
    print(f"Uso de Memoria: {uso_memoria:.2f} MB")
    print(f"Tasa de Error: {errores / total_predicciones * 100:.2f}%")

    cam.release()
    cv2.destroyAllWindows()

# Ejecutar la cámara, evaluando el color rojo
if __name__ == "__main__":
    iniciarCamara(color_objetivo='rojo')  # Puedes cambiar 'rojo' por 'amarillo' o 'verde'


Iniciando módulo
Cámara abierta
Pesos de la red Hopfield cargados correctamente.

Criterios Cuantitativos para el color Rojo:
Precisión: 46.00%
Latencia Media: 0.03 ms
Uso de CPU: 3.10%
Uso de Memoria: 125.28 MB
Tasa de Error: 54.00%


In [ ]:
#red de base radial

In [9]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
import joblib
import time
import psutil  # Para medir el uso de recursos

# Datos sintéticos: colores ajustados para mejorar la diferenciación
X = np.array([
    # ROJO (alto R, bajo G, bajo B)
    [255, 50, 50],          # rojo claro
    [210, 40, 40],          # rojo medio
    [200, 30, 30],          # rojo suave
    [230, 70, 60],          # rojo brillante
    [220, 60, 50],          # rojo con más naranja
    [235, 20, 20],          # rojo más fuerte
    [240, 10, 10],          # rojo oscuro
    [245, 60, 50],          # rojo cálido
    [230, 50, 40],          # rojo anaranjado
    [250, 30, 20],          # rojo brillante

    # AMARILLO (alto R, alto G, bajo B)
    [255, 255, 20],         # amarillo cálido
    [255, 255, 40],         # amarillo más saturado
    [255, 240, 60],         # amarillo suave
    [255, 230, 80],         # amarillo más verde
    [250, 245, 50],         # amarillo oscuro
    [240, 255, 80],         # amarillo más verde
    [245, 255, 60],         # amarillo con más verde
    [255, 220, 40],         # amarillo más rojo
    [255, 255, 80],         # amarillo más claro
    [250, 230, 20],         # amarillo cálido y profundo

    # VERDE (bajo R, alto G, bajo B)
    [0, 255, 20],           # verde claro
    [10, 230, 20],          # verde medio
    [0, 200, 20],           # verde oscuro
    [30, 240, 30],          # verde brillante
    [10, 210, 10],          # verde suave
    [5, 255, 5],            # verde saturado
    [20, 235, 20],          # verde cálido
    [10, 250, 30],          # verde brillante
    [0, 180, 0],            # verde profundo
    [25, 240, 25],          # verde con más azul
])

# Etiquetas: 0=rojo, 1=amarillo, 2=verde
y = np.array(
    [0]*10 +  # rojo
    [1]*10 +  # amarillo
    [2]*10    # verde
)

# Clustering para obtener los centros RBF
n_centros = 8  # Aumentar el número de centros para mejorar la clasificación
kmeans = KMeans(n_clusters=n_centros, random_state=42).fit(X)
centros = kmeans.cluster_centers_

def rbf(x, centro, sigma=100.0):
    return np.exp(-np.linalg.norm(x - centro)**2 / (2 * sigma**2))

def transformar_con_rbf(X):
    return np.array([[rbf(x, c) for c in centros] for x in X])

# Transformar los datos con la capa RBF
X_rbf = transformar_con_rbf(X)

# Clasificador
modelo = LogisticRegression(max_iter=100000)

# Medir el tiempo de entrenamiento
inicio = time.time()
modelo.fit(X_rbf, y)
fin = time.time()

# Guardar modelo
joblib.dump(modelo, 'entrenamientos_guardados/modelo_rbf.pkl')
joblib.dump(centros, 'entrenamientos_guardados/centros_rbf.pkl')

# Medir el uso de CPU y memoria durante el entrenamiento
cpu_usage = psutil.cpu_percent(interval=1)
memory_usage = psutil.virtual_memory().percent

# Calcular el tiempo de entrenamiento
tiempo_entrenamiento = fin - inicio

# Mostrar los resultados del entrenamiento
print(f"✅ Modelo RBF entrenado con colores más diferenciados.")
print(f"⏱️ Tiempo de Entrenamiento: {tiempo_entrenamiento:.4f} segundos.")
print(f"💻 Uso de CPU durante entrenamiento: {cpu_usage}%")
print(f"💾 Uso de Memoria durante entrenamiento: {memory_usage}%")


✅ Modelo RBF entrenado con colores más diferenciados.
⏱️ Tiempo de Entrenamiento: 0.0050 segundos.
💻 Uso de CPU durante entrenamiento: 13.0%
💾 Uso de Memoria durante entrenamiento: 62.0%


In [8]:
import cv2
import numpy as np
import joblib

# Cargar el modelo entrenado
modelo = joblib.load('entrenamientos_guardados/modelo_rbf.pkl')
centros = joblib.load('entrenamientos_guardados/centros_rbf.pkl')

def rbf(x, centro, sigma=100.0):
    return np.exp(-np.linalg.norm(x - centro)**2 / (2 * sigma**2))

def transformar_con_rbf(X):
    return np.array([[rbf(x, c) for c in centros] for x in X])

def preprocesar_imagen(frame):
    # Convertir la imagen a HSV para hacer la detección más robusta
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # Definir los rangos de color de los semáforos en HSV
    rango_rojo_bajo = np.array([0, 100, 100])
    rango_rojo_alto = np.array([10, 255, 255])
    rango_amarillo_bajo = np.array([20, 100, 100])
    rango_amarillo_alto = np.array([40, 255, 255])
    rango_verde_bajo = np.array([40, 100, 100])
    rango_verde_alto = np.array([80, 255, 255])

    # Crear máscaras para cada color
    mascara_rojo = cv2.inRange(hsv, rango_rojo_bajo, rango_rojo_alto)
    mascara_amarillo = cv2.inRange(hsv, rango_amarillo_bajo, rango_amarillo_alto)
    mascara_verde = cv2.inRange(hsv, rango_verde_bajo, rango_verde_alto)

    # Filtrar los colores para obtener solo el predominante
    predom_color = None
    if cv2.countNonZero(mascara_rojo) > max(cv2.countNonZero(mascara_amarillo), cv2.countNonZero(mascara_verde)):
        predom_color = [0]  # Rojo
    elif cv2.countNonZero(mascara_amarillo) > max(cv2.countNonZero(mascara_rojo), cv2.countNonZero(mascara_verde)):
        predom_color = [1]  # Amarillo
    else:
        predom_color = [2]  # Verde

    return predom_color

def detectar_color(frame):
    # Redimensionar para acelerar
    img = cv2.resize(frame, (100, 100))
    # Calcular color promedio
    promedio = img.mean(axis=0).mean(axis=0)  # BGR
    promedio_rgb = promedio[::-1]  # Convertir a RGB
    X_test = transformar_con_rbf([promedio_rgb])
    pred = modelo.predict(X_test)[0]
    return pred

def advertir_color(color_id):
    if color_id == 0:
        return "DETECTADO: ROJO - DETENER"
    elif color_id == 1:
        return "DETECTADO: AMARILLO - PRECAUCION"
    elif color_id == 2:
        return "DETECTADO: VERDE - AVANZAR"
    return "Color no identificado"

def iniciarCamara():
    print("🔧 Iniciando cámara...")
    cam = cv2.VideoCapture(0)
    if not cam.isOpened():
        print("❌ No se pudo abrir la cámara")
        return
    print("✅ Cámara abierta")

    while True:
        ret, frame = cam.read()
        if not ret:
            print("❌ Error al capturar imagen")
            break

        # Preprocesar la imagen para detectar el color predominante
        color_id = preprocesar_imagen(frame)

        mensaje = advertir_color(color_id[0])

        # Mostrar cámara y mensaje
        cv2.putText(frame, mensaje, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 255), 2)
        cv2.imshow("Camara Semaforo RBF", frame)

        if cv2.waitKey(1) & 0xFF == 27:  # ESC para salir
            break

    cam.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    iniciarCamara()


🔧 Iniciando cámara...
✅ Cámara abierta


In [11]:
import cv2
import numpy as np
import joblib
import time
import psutil  # Para medir el uso de recursos

# Cargar el modelo entrenado
modelo = joblib.load('entrenamientos_guardados/modelo_rbf.pkl')
centros = joblib.load('entrenamientos_guardados/centros_rbf.pkl')

def rbf(x, centro, sigma=100.0):
    return np.exp(-np.linalg.norm(x - centro)**2 / (2 * sigma**2))

def transformar_con_rbf(X):
    return np.array([[rbf(x, c) for c in centros] for x in X])

def preprocesar_imagen(frame):
    # Convertir la imagen a HSV para hacer la detección más robusta
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # Definir los rangos de color de los semáforos en HSV
    rango_rojo_bajo = np.array([0, 100, 100])
    rango_rojo_alto = np.array([10, 255, 255])
    rango_amarillo_bajo = np.array([20, 100, 100])
    rango_amarillo_alto = np.array([40, 255, 255])
    rango_verde_bajo = np.array([40, 100, 100])
    rango_verde_alto = np.array([80, 255, 255])

    # Crear máscaras para cada color
    mascara_rojo = cv2.inRange(hsv, rango_rojo_bajo, rango_rojo_alto)
    mascara_amarillo = cv2.inRange(hsv, rango_amarillo_bajo, rango_amarillo_alto)
    mascara_verde = cv2.inRange(hsv, rango_verde_bajo, rango_verde_alto)

    # Filtrar los colores para obtener solo el predominante
    predom_color = None
    if cv2.countNonZero(mascara_rojo) > max(cv2.countNonZero(mascara_amarillo), cv2.countNonZero(mascara_verde)):
        predom_color = [0]  # Rojo
    elif cv2.countNonZero(mascara_amarillo) > max(cv2.countNonZero(mascara_rojo), cv2.countNonZero(mascara_verde)):
        predom_color = [1]  # Amarillo
    else:
        predom_color = [2]  # Verde

    return predom_color

def detectar_color(frame):
    # Redimensionar para acelerar
    img = cv2.resize(frame, (100, 100))
    # Calcular color promedio
    promedio = img.mean(axis=0).mean(axis=0)  # BGR
    promedio_rgb = promedio[::-1]  # Convertir a RGB
    X_test = transformar_con_rbf([promedio_rgb])
    pred = modelo.predict(X_test)[0]
    return pred

def advertir_color(color_id):
    if color_id == 0:
        return "DETECTADO: ROJO - DETENER"
    elif color_id == 1:
        return "DETECTADO: AMARILLO - PRECAUCION"
    elif color_id == 2:
        return "DETECTADO: VERDE - AVANZAR"
    return "Color no identificado"

def iniciarCamara():
    print("🔧 Iniciando cámara...")
    cam = cv2.VideoCapture(0)
    if not cam.isOpened():
        print("❌ No se pudo abrir la cámara")
        return
    print("✅ Cámara abierta")

    predicciones_correctas = 0
    total_predicciones = 0
    errores = 0

    while True:
        ret, frame = cam.read()
        if not ret:
            print("❌ Error al capturar imagen")
            break

        # Medir el tiempo de procesamiento por frame
        inicio_frame = time.time()

        # Preprocesar la imagen para detectar el color predominante
        color_id = preprocesar_imagen(frame)

        mensaje = advertir_color(color_id[0])

        # Calcular el color promedio y hacer la predicción
        pred = detectar_color(frame)
        total_predicciones += 1
        if pred == color_id[0]:
            predicciones_correctas += 1
        else:
            errores += 1

        # Mostrar cámara y mensaje
        cv2.putText(frame, mensaje, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 255), 2)
        cv2.imshow("Camara Semaforo RBF", frame)

        # Medir el tiempo de ejecución por frame
        fin_frame = time.time()
        tiempo_frame = (fin_frame - inicio_frame) * 1000  # En milisegundos

        if cv2.waitKey(1) & 0xFF == 27:  # ESC para salir
            break

    cam.release()
    cv2.destroyAllWindows()

    # Calcular precisión y tasa de error
    precision = predicciones_correctas / total_predicciones
    tasa_error = errores / total_predicciones

    # Medir el uso de CPU y memoria
    cpu_usage = psutil.cpu_percent(interval=1)
    memory_usage = psutil.virtual_memory().percent

    print(f"✅ Evaluación final:")
    print(f"   Precisión: {precision * 100:.2f}%")
    print(f"   Tasa de error: {tasa_error * 100:.2f}%")
    print(f"   Tiempo de ejecución promedio por frame: {tiempo_frame:.2f} ms")
    print(f"   Uso de CPU: {cpu_usage}%")
    print(f"   Uso de memoria: {memory_usage}%")

if __name__ == "__main__":
    iniciarCamara()


🔧 Iniciando cámara...
✅ Cámara abierta
✅ Evaluación final:
   Precisión: 52.06%
   Tasa de error: 47.94%
   Tiempo de ejecución promedio por frame: 2.00 ms
   Uso de CPU: 51.5%
   Uso de memoria: 62.3%


In [ ]:
#red de mapa autorganizados

In [1]:
# train_som.py
import numpy as np
from minisom import MiniSom
import pickle

def generate_color_samples(center_rgb, spread=20, n_samples=500):
    samples = np.clip(
        np.random.randint(center_rgb - spread, center_rgb + spread + 1,
                          size=(n_samples, 3)),
        0, 255
    )
    return samples

def main():
    centers = {
        'ROJO':    np.array([255,   0,   0]),
        'AMARILLO':np.array([255, 255,   0]),
        'VERDE':   np.array([  0, 255,   0]),
    }

    # Generar muestras y normalizar
    data = []
    for c in centers.values():
        data.append(generate_color_samples(c))
    data = np.vstack(data) / 255.0

    # SOM de 3x1 con sigma mayor para mejor separación
    som = MiniSom(3, 1, 3, sigma=1.0, learning_rate=0.5)
    som.random_weights_init(data)
    print("Entrenando SOM (5 000 iters)...")
    som.train_random(data, num_iteration=5000)
    print("Entrenamiento completado.")

    # Mapeo neurona → etiqueta
    mapping = {}
    for label, center in centers.items():
        win = som.winner(center / 255.0)
        mapping[win] = label

    with open('entrenamientos_guardados/som_traffic_light.pkl', 'wb') as f:
        pickle.dump({'som': som, 'mapping': mapping}, f)
    print("Modelo guardado en 'som_traffic_light.pkl'.")

if __name__ == '__main__':
    main()


Entrenando SOM (5 000 iters)...
Entrenamiento completado.
Modelo guardado en 'som_traffic_light.pkl'.


In [1]:
# run_traffic_light_som.py
import cv2
import numpy as np
import pickle
from collections import Counter

def load_model(path='som_traffic_light.pkl'):
    with open(path, 'rb') as f:
        data = pickle.load(f)
    return data['som'], data['mapping']

def main():
    som, mapping = load_model()
    cam = cv2.VideoCapture(0)
    if not cam.isOpened():
        print("No se pudo abrir la cámara")
        return

    print("Cámara iniciada. Presiona ESC para salir.")
    while True:
        ret, frame = cam.read()
        if not ret:
            print("Error capturando frame")
            break

        # 1) Convertir frame a RGB normalizado
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) / 255.0
        h, w, _ = rgb.shape

        # 2) Muestrear aleatoriamente 5000 píxeles
        coords = np.random.randint(0, h*w, size=5000)
        pixels = rgb.reshape(-1, 3)[coords]

        # 3) Para cada píxel, obtener la neurona ganadora
        wins = [som.winner(p) for p in pixels]
        labels = [mapping.get(w, 'DESCONOCIDO') for w in wins]

        # 4) Contar y elegir la etiqueta más frecuente
        most_common = Counter(labels).most_common(1)[0][0]

        # 5) Dibujar resultado en el frame
        color_text = {'ROJO':(0,0,255), 'AMARILLO':(0,255,255), 'VERDE':(0,255,0)}.get(most_common, (255,255,255))
        cv2.putText(frame, f'Luz: {most_common}',
                    (10,30), cv2.FONT_HERSHEY_SIMPLEX, 1, color_text, 2)

        cv2.imshow("Detección Semáforo", frame)
        if cv2.waitKey(1) & 0xFF == 27:
            break

    cam.release()
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main()


Cámara iniciada. Presiona ESC para salir.


a
